version: "3"

services:
  api:
    build: ./api_projects
    container_name: api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./api_projects:/api_backend
  api_chat:
    build: ./api_projects/flask_chat_app
    container_name: api_chat
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./api_projects/flask_chat_app:/api_chat
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - api
      - api_chat
  redis:
    image: redis
    container_name: redis
    command:
      - redis-server
      - --databases
      - "300"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
      - /etc/localtime:/etc/localtime:ro
